### ISSUE TITLE
Lab 7 - unable to generate the Entities.cs file with the Early Bound Generator from Daryl LaBar

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#152]
This is new ,a month ago this was working properly. It is not possible to generate the Entities.cs, however the Optionsets.cs are working.

Generating the Entities.cs fails with the following error message:

You are running V1 of the XTB Early Bound Generator.  If you Please consider upgrading to V2, which is much faster and has many more features!
You are using an older, slower version of the the Early Bound Generator.  Please consider installing the Early Bound Generator V2 from the XrmToolBox plugin store!
CRM Authentication Type Detected: OnlineFederation
Tracking Entities Generation Event.
Executing for Entities
Executing "C:\Users\Admin\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://orge5ef9d31.api.crm4.dynamics.com" /namespace:"CrmEarlyBound" /SuppressGeneratedCodeAttribute /out:"C:\Users\Admin\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Entities.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"admin@M365x64344437.onmicrosoft.com" /password:"******************" 
CrmSvcUtil : CRM Service Utility [Version 9.1.0.95]
c 2020 Microsoft Corporation. All rights reserved

Begin Reading Metadata
Begin Reading Metadata from Server
Completed Reading Metadata from Server - 00:00:37.2126201
Completed Reading Metadata 00:00:41.0757670
Begin Writing File
 Ensuring Context File is Accessible 
 Writing file Entities.cs to C:\Users\Admin\AppData\Local\Temp\tmpDFF7.tmp 
Processing 141 OptionSets
Wrote 0 OptionSets
Processing 723 Entities
Wrote 7 Entities
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at DLaB.CrmSvcUtilExtensions.Entity.MultiOptionSetAttributeUpdater.<>c.<CustomizeCodeDom>b__0_1(EntityMetadata v)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at DLaB.CrmSvcUtilExtensions.Entity.MultiOptionSetAttributeUpdater.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Completed Writing File 00:00:01.0929330
Output file was not updated or not found!  C:\Users\Admin\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Entities.cs
Creation Complete!

**Comment by julians1966** [comment]
The lab was updated a few weeks ago by PR #142 to remove early bound and use of the Early Bound Generator
If you are still seeing this in your lab environment, contact the ALH to update their lab steps

**Comment by RobertRybaric** [comment]
> The lab was updated a few weeks ago by PR #142 to remove early bound and use of the Early Bound Generator If you are still seeing this in your lab environment, contact the ALH to update their lab steps

Thanks Julian, I see that goDeploy has not updated anything, also from my previous batch of issues.

**Comment by julians1966** [comment]
I have raiseds a ticket with them to make the updates
GDS-8041

**Comment by julians1966** [comment]
Received update from GoDeploy

"The content team have made the necessary changes to Lab 7 of PL-400. The 2nd task within the lab has been made redundant and therefore has been removed. The rest of the lab reflects what is seen on GitHub."
